apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ag6fegsx4-go-gitops
  description: This is GitOps manifest for ag6fegsx4-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=ag6fegsx4-go
    backstage.io/kubernetes-id: ag6fegsx4-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ag6fegsx4-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ag6fegsx4-go
